name: Auto Measure

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "mode (c4_impl | c5_cases | c6_salvage | c7_semantic | bench)"
        required: true
        default: "c7_semantic"
      target_id:
        description: "target id (used only by legacy modes)"
        required: false
        default: "all"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # C7 で追加
          pip install pyyaml sentence-transformers numpy

      # ---- C7: semantic claims rescue --------------------------------
      - name: Run C7 (c7_semantic)
        if: ${{ github.event.inputs.mode == 'c7_semantic' }}
        run: |
          set -e
          echo ">>> python scripts/c7_semantic.py"
          python scripts/c7_semantic.py

      # ---- C6: salvage -----------------------------------------------
      - name: Run C6 (c6_salvage)
        if: ${{ github.event.inputs.mode == 'c6_salvage' }}
        run: |
          set -e
          python scripts/c6_salvage.py

      # ---- C5: cases -------------------------------------------------
      - name: Run C5 (c5_cases)
        if: ${{ github.event.inputs.mode == 'c5_cases' }}
        run: |
          set -e
          python scripts/c5_cases.py

      # ---- legacy modes via run_common.py ----------------------------
      - name: Run legacy modes
        if: ${{ github.event.inputs.mode != 'c7_semantic' && github.event.inputs.mode != 'c6_salvage' && github.event.inputs.mode != 'c5_cases' }}
        run: |
          set -e
          echo ">>> legacy mode not configured in this workflow"

      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            outputs/**
            docs/figs/**
          if-no-files-found: warn
