name: Auto Measure

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "mode (toy | n_r | c4_impl | bench | c5_cases | c6_salvage)"
        required: true
        default: "c6_salvage"
      target_id:
        description: "target id (for c4_impl / n_r / bench)"
        required: false
        default: "brand_larica"
      kappa_list:
        description: "Comma-separated kappas (for n_r only)"
        required: false
        default: ""
      bp_path:
        description: "BP yaml path (for c4_impl / n_r / bench)"
        required: false
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyyaml

      # --- C6: salvage（非構造文の救済測定） -------------------------
      - name: Run C6 (c6_salvage)
        if: ${{ github.event.inputs.mode == 'c6_salvage' }}
        run: |
          set -e
          echo ">>> python scripts/c6_salvage.py"
          python scripts/c6_salvage.py

      # --- C5: 複数ケース一般化（GEN） -------------------------------
      - name: Run C5 (c5_cases)
        if: ${{ github.event.inputs.mode == 'c5_cases' }}
        run: |
          set -e
          echo ">>> python scripts/c5_cases.py"
          python scripts/c5_cases.py

      # --- 従来モード（run_common.py 経由） -------------------------
      - name: Run legacy modes via run_common.py
        if: ${{ github.event.inputs.mode != 'c6_salvage' && github.event.inputs.mode != 'c5_cases' }}
        env:
          MODE:       ${{ github.event.inputs.mode }}
          TARGET_ID:  ${{ github.event.inputs.target_id }}
          KAPPA_LIST: ${{ github.event.inputs.kappa_list }}
          BP_PATH:    ${{ github.event.inputs.bp_path }}
        run: |
          set -e
          ARGS="--mode ${MODE}"
          if [ -n "${TARGET_ID}" ]; then
            ARGS="${ARGS} --target_id ${TARGET_ID}"
          fi
          if [ -n "${KAPPA_LIST}" ]; then
            ARGS="${ARGS} --kappa_list \"${KAPPA_LIST}\""
          fi
          if [ -n "${BP_PATH}" ]; then
            ARGS="${ARGS} --bp_path \"${BP_PATH}\""
          fi
          echo ">>> python run_common.py ${ARGS}"
          eval python run_common.py ${ARGS}

      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            outputs/**
            docs/figs/**
          if-no-files-found: warn
