name: Auto Measure

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "mode (toy | n_r | c4_impl | bench)"
        required: true
        default: "c4_impl"
      target_id:
        description: "target id (e.g. brand_larica)"
        required: false
        default: "brand_larica"
      kappa_list:
        description: "Comma-separated kappas (for n_r only)"
        required: false
        default: ""
      bp_path:
        description: "BP yaml path (optional; default: outputs/c2_manual/bp_<target_id>.yaml)"
        required: false
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run AutoMeasure
        env:
          MODE:       ${{ github.event.inputs.mode }}
          TARGET_ID:  ${{ github.event.inputs.target_id }}
          KAPPA_LIST: ${{ github.event.inputs.kappa_list }}
          BP_PATH:    ${{ github.event.inputs.bp_path }}
        run: |
          set -e
          ARGS="--mode ${MODE}"
          if [ -n "${TARGET_ID}" ]; then
            ARGS="${ARGS} --target_id ${TARGET_ID}"
          fi
          if [ -n "${KAPPA_LIST}" ]; then
            ARGS="${ARGS} --kappa_list \"${KAPPA_LIST}\""
          fi
          echo ">>> python run_common.py ${ARGS}"
          eval python run_common.py ${ARGS}

      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            outputs/**
            docs/figs/**
          if-no-files-found: warn
