# 既存部はそのまま。mode の候補に c6_salvage を追加しておくと親切です。
# ...
      mode:
        description: "mode (toy | n_r | c4_impl | bench | c5_cases | c6_salvage)"
        required: true
        default: "c6_salvage"
# ...

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyyaml

      # --- C6: salvage（非構造文救済） -------------------------------
      - name: Run C6 (c6_salvage)
        if: ${{ github.event.inputs.mode == 'c6_salvage' }}
        run: |
          set -e
          echo ">>> python scripts/c6_salvage.py"
          python scripts/c6_salvage.py

      # --- 既存（C5/C4等）は従来どおり -------------------------------
      - name: Run C5 (c5_cases)
        if: ${{ github.event.inputs.mode == 'c5_cases' }}
        run: |
          set -e
          python scripts/c5_cases.py

      - name: Run legacy modes via run_common.py
        if: ${{ github.event.inputs.mode != 'c6_salvage' && github.event.inputs.mode != 'c5_cases' }}
        env:
          MODE:       ${{ github.event.inputs.mode }}
          TARGET_ID:  ${{ github.event.inputs.target_id }}
          KAPPA_LIST: ${{ github.event.inputs.kappa_list }}
          BP_PATH:    ${{ github.event.inputs.bp_path }}
        run: |
          set -e
          ARGS="--mode ${MODE}"
          if [ -n "${TARGET_ID}" ]; then
            ARGS="${ARGS} --target_id ${TARGET_ID}"
          fi
          if [ -n "${KAPPA_LIST}" ]; then
            ARGS="${ARGS} --kappa_list \"${KAPPA_LIST}\""
          fi
          if [ -n "${BP_PATH}" ]; then
            ARGS="${ARGS} --bp_path \"${BP_PATH}\""
          fi
          echo ">>> python run_common.py ${ARGS}"
          eval python run_common.py ${ARGS}
