name: Auto Measure

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "mode (e.g. toy | n_r)"
        required: true
        default: "n_r"
      target_id:
        description: "target id (e.g. lari_001) — optional"
        required: false
        default: ""
      kappa_list:
        description: "Comma-separated kappas (e.g. 0.0,0.2,0.4,0.6,0.8,1.0) — optional; leave blank to use defaults"
        required: false
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run AutoMeasure
        env:
          MODE: ${{ github.event.inputs.mode }}
          TARGET_ID: ${{ github.event.inputs.target_id }}
          KAPPA_LIST: ${{ github.event.inputs.kappa_list }}
        run: |
          set -e
          ARGS="--mode ${MODE}"
          if [ -n "${TARGET_ID}" ]; then
            ARGS="${ARGS} --target_id ${TARGET_ID}"
          fi
          if [ -n "${KAPPA_LIST}" ]; then
            # pass as one quoted string so commas are preserved
            ARGS="${ARGS} --kappa_list \"${KAPPA_LIST}\""
          fi
          echo ">>> python run_common.py ${ARGS}"
          eval python run_common.py ${ARGS}

      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            outputs/**
            docs/figs/**
          if-no-files-found: warn

# 既存の run step の最後に追記
      - name: Run BP Layer
        if: ${{ github.event.inputs.mode == 'bp_layer' }}
        run: |
          python scripts/run_bp_layer.py --target_id lari_001 --bp_path outputs/c2_manual/bp_larica.yaml
