name: Publish Pages

on:
  workflow_dispatch:
    inputs:
      MODE:
        description: 'toy / n_r / bench'
        required: false
        default: 'toy'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODE: ${{ github.event.inputs.MODE || 'toy' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline (produce outputs/ and figs/)
        run: python run_common.py

      - name: Build static site bundle
        run: |
          set -e
          mkdir -p site
          REPO="${{ github.repository }}"
          BADGE="https://github.com/${REPO}/actions/workflows/auto.yml/badge.svg?branch=main"
          ART1="outputs/${{ env.MODE }}/metrics.json"
          FIG1="figs/${{ env.MODE }}/fig_C1_2.svg"
          echo "<!doctype html><meta charset='utf-8'>"                           > site/index.html
          echo "<h1>Forgetting Mechanics — Auto Base (${MODE})</h1>"             >> site/index.html
          echo "<p><img src='${BADGE}' alt='Auto Measure Status'></p>"           >> site/index.html
          echo "<ul>"                                                            >> site/index.html
          echo "<li><a href='${ART1}'>${ART1}</a></li>"                          >> site/index.html
          if [ -f "${FIG1}" ]; then echo "<li><a href='${FIG1}'>${FIG1}</a></li>" >> site/index.html; fi
          echo "</ul><p>Generated by Publish Pages workflow.</p>"                >> site/index.html
          mkdir -p site/outputs site/figs
          cp -r outputs/${{ env.MODE }} site/outputs/ || true
          cp -r figs/${{ env.MODE }} site/figs/ || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
